"""empty message

Revision ID: 847217855ec7
Revises: 
Create Date: 2024-07-09 11:09:19.488740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847217855ec7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_time', sa.Date(), nullable=False),
    sa.Column('number_gests', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_reservation_customer_id_customer')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name=op.f('fk_reservation_restaurant_id_restaurant')),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], name=op.f('fk_reservation_table_id_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], name=op.f('fk_reservation_table_reservation_id_reservation')),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], name=op.f('fk_reservation_table_table_id_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation_table')
    op.drop_table('reservation')
    op.drop_table('table')
    op.drop_table('restaurant')
    op.drop_table('customer')
    # ### end Alembic commands ###
